### DISCUSSION TITLE
定刻にActionsでPRを出す

### DISCUSSION THREAD

**Discussion by hayashi3017** [hayashi3017/sandbox#51] [General]
https://zenn.dev/no4_dev/articles/14b295b8dafbfd

scheduleでスクリプトをキックする
https://github.com/reactjs/translations.react.dev/blob/4e85e8dcc1069e8b5d58e1c0db21104471e54b96/.github/workflows/sync-batch-1.yml

**Comment by hayashi3017** [comment]
自動コミット＆PR作成の例

```
name: foo

on:
  push:
  workflow_dispatch:

jobs:
  foo:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: foo
        run: |
          bash <foo script> 
      - name: Commit
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "foo"
          git push
  create-pr:
    needs: foo
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Check PR
       # master向けのPRが作成されていないことを確認する
        run: echo "is_pr_opened=$(gh pr list -B master -H ${{ github.ref_name }} --state open | wc -l)" >> $GITHUB_ENV
      - name: Create PR
        if: env.is_pr_opened == 0
　　# master向けのPRを作成する
        run: gh pr create -B "master" -t "foo" -F .github/PULL_REQUEST_TEMPLATE.md
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
